workflows:
  ios-build:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Generate iOS project
        script: flutter create . --platforms=ios --project-name=digit_app --org=com.shuffledfusion
      - name: Restore custom files
        script: |
          cp -f ios/Runner/AppDelegate.custom.swift ios/Runner/AppDelegate.swift
      - name: Add LibTorch to Podfile
        script: |
          echo "pod 'LibTorch-Lite', '~>2.3.0'" | cat - ios/Podfile > ios/Podfile.tmp
          mv ios/Podfile.tmp ios/Podfile
      - name: Pod install
        script: cd ios && pod install
      - name: Flutter pub get
        script: flutter pub get
      - name: Build iOS
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
