workflows:
  ios-build:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Create iOS project
        script: flutter create . --platforms=ios --project-name=digit_app --org=com.shuffledfusion
      - name: Use correct Podfile
        script: cp -f ios/Podfile.fixed ios/Podfile
      - name: Flutter pub get
        script: flutter pub get
      - name: Pod install
        script: cd ios && pod install
      - name: Build iOS
        script: flutter build ios --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - 33122@qq.com