platform :ios, '16.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # LibTorch for loading .pt models
  pod 'LibTorch-Lite', '~>2.3.0'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
